spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/test}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:5233}
spring.datasource.driver-class-name=org.postgresql.Driver

# Enable schema.sql initialization on startup for non-embedded databases (PostgreSQL)
spring.sql.init.mode=always

# Enable SQL logging for Spring Data JDBC
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG