spring.data.jdbc.dialect=postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=5233
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# YouTube Integration Configuration
youtube.api-key=${YOUTUBE_API_KEY:}
youtube.channel-id=${YOUTUBE_CHANNEL_ID:}